name: K-Pop Database Sync

on:
  schedule:
    # midnight every monday is 3 pm UTC on Sunday
    - cron: '0 15 * * 0'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install all dependencies (pnpm)
        uses: pnpm/action-setup@v4
      - name: Run mysql2db script & create new DB
        run: pnpm tsx ./scripts/mysql2db.ts
      - name: Commit new DB (triggers labeler update)
        run: echo 'not implemented yet'
